### ISSUE TITLE
Exceptions are thrown causing the UI to be slow

### ISSUE THREAD

**Issue by ursuad** [aseigneurin/spark-ui-proxy#2]
Hi, this is exactly what I was looking for, but I found a small issue:

**Current setup**
I'm running the following on Kubernetes:

1 spark master: 10.70.19.3, DNS: spark-master
3 spark workers: 10.70.23.3, 10.70.20.3, 10.70.19.4
1 spark-proxy-ui: 10.70.23.4

**Test Case**
1) Access the spark proxy UI --> The Spark Webui load successfully.
2) Click on a link for a worker --> The Worker page loads
3) Click on the "Back to Master" --> This is slow because exceptions are thrown, but after a while it redirects back
4) Click on a different worker link --> The worker page loads (sometimes, exceptions are thrown here also)
5) Click on "Back to Master" -- Same behaviour, with exceptions

Sometime, exceptions are thrown when I click on the worker links, so "Back to Master" it's not necessarily the only issue. 

**Logs for the test case**

You can find the logs  from the spark-proxy-ui for my test case below: 

```
$ kubectl logs -f spark-proxy-ui-controller-09ju8
Starting server on http://0.0.0.0:80
10.70.28.0 - - [22/Sep/2016 13:31:26] "GET /proxy:10.70.23.3:8081 HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/bootstrap.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/webui.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/vis.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/timeline-view.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/jquery-1.11.1.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/sorttable.js HTTP/1.1" 200 -
get: /proxy:10.70.23.3:8081
host: 10.70.23.3:8081
path:
target: http://10.70.23.3:8081
get: /proxy:10.70.23.3:8081/static/bootstrap.min.css
host: 10.70.23.3:8081
path: /static/bootstrap.min.css
target: http://10.70.23.3:8081/static/bootstrap.min.css
get: /proxy:10.70.23.3:8081/static/webui.css
host: 10.70.23.3:8081
path: /static/webui.css
target: http://10.70.23.3:8081/static/webui.css
get: /proxy:10.70.23.3:8081/static/vis.min.css
host: 10.70.23.3:8081
path: /static/vis.min.css
target: http://10.70.23.3:8081/static/vis.min.css
get: /proxy:10.70.23.3:8081/static/timeline-view.css
host: 10.70.23.3:8081
path: /static/timeline-view.css
target: http://10.70.23.3:8081/static/timeline-view.css
get: /proxy:10.70.23.3:8081/static/jquery-1.11.1.min.js
host: 10.70.23.3:8081
path: /static/jquery-1.11.1.min.js
target: http://10.70.23.3:8081/static/jquery-1.11.1.min.js
get: /proxy:10.70.23.3:8081/static/sorttable.js
host: 10.70.23.3:8081
path: /static/sorttable.js
target: http://10.70.23.3:8081/static/sorttable.js
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/vis.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/bootstrap-tooltip.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/initialize-tooltips.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/table.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/additional-metrics.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:27] "GET /proxy:10.70.23.3:8081/static/timeline-view.js HTTP/1.1" 200 -
get: /proxy:10.70.23.3:8081/static/vis.min.js
host: 10.70.23.3:8081
path: /static/vis.min.js
target: http://10.70.23.3:8081/static/vis.min.js
get: /proxy:10.70.23.3:8081/static/bootstrap-tooltip.js
host: 10.70.23.3:8081
path: /static/bootstrap-tooltip.js
target: http://10.70.23.3:8081/static/bootstrap-tooltip.js
get: /proxy:10.70.23.3:8081/static/initialize-tooltips.js
host: 10.70.23.3:8081
path: /static/initialize-tooltips.js
target: http://10.70.23.3:8081/static/initialize-tooltips.js
get: /proxy:10.70.23.3:8081/static/table.js
host: 10.70.23.3:8081
path: /static/table.js
target: http://10.70.23.3:8081/static/table.js
get: /proxy:10.70.23.3:8081/static/additional-metrics.js
host: 10.70.23.3:8081
path: /static/additional-metrics.js
target: http://10.70.23.3:8081/static/additional-metrics.js
get: /proxy:10.70.23.3:8081/static/timeline-view.js
host: 10.70.23.3:8081
path: /static/timeline-view.js
target: http://10.70.23.3:8081/static/timeline-view.js
get: /proxy:10.70.23.3:8081/static/spark-logo-77x50px-hd.png
host: 10.70.23.3:8081
10.70.28.0 - - [22/Sep/2016 13:31:28] "GET /proxy:10.70.23.3:8081/static/spark-logo-77x50px-hd.png HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:28] "GET /favicon.ico HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:35] "GET /proxy:spark-master:8080 HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:36] "GET /proxy:spark-master:8080/static/bootstrap.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:39] "GET /proxy:spark-master:8080/static/vis.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:39] "GET /proxy:spark-master:8080/static/webui.css HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/spark-ui-proxy.py", line 19, in do_GET
    self.proxyRequest(None)
  File "/spark-ui-proxy.py", line 35, in proxyRequest
    proxiedRequest = urllib2.urlopen(targetUrl, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Try again>
path: /static/spark-logo-77x50px-hd.png
target: http://10.70.23.3:8081/static/spark-logo-77x50px-hd.png
get: /favicon.ico
host: spark-master:8080
path: /favicon.ico
target: http://spark-master:8080/favicon.ico
get: /proxy:spark-master:8080
host: spark-master:8080
path:
target: http://spark-master:8080
get: /proxy:spark-master:8080/static/bootstrap.min.css
host: spark-master:8080
path: /static/bootstrap.min.css
target: http://spark-master:8080/static/bootstrap.min.css
get: /proxy:spark-master:8080/static/vis.min.css
host: spark-master:8080
path: /static/vis.min.css
target: http://spark-master:8080/static/vis.min.css
get: /proxy:spark-master:8080/static/webui.css
host: spark-master:8080
path: /static/webui.css
target: http://spark-master:8080/static/webui.css
get: /proxy:spark-master:8080/static/timeline-view.css
host: spark-master:8080
path: /static/timeline-view.css
target: http://spark-master:8080/static/timeline-view.css
----------------------------------------
Exception happened during processing of request from ('10.70.28.0', 53652)
10.70.28.0 - - [22/Sep/2016 13:31:44] "GET /proxy:spark-master:8080/static/sorttable.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:44] "GET /proxy:spark-master:8080/static/jquery-1.11.1.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:45] "GET /proxy:spark-master:8080/static/vis.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:45] "GET /proxy:spark-master:8080/static/bootstrap-tooltip.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:45] "GET /proxy:spark-master:8080/static/table.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:49] "GET /proxy:spark-master:8080/static/initialize-tooltips.js HTTP/1.1" 200 -
----------------------------------------
get: /proxy:spark-master:8080/static/sorttable.js
host: spark-master:8080
path: /static/sorttable.js
target: http://spark-master:8080/static/sorttable.js
get: /proxy:spark-master:8080/static/jquery-1.11.1.min.js
host: spark-master:8080
path: /static/jquery-1.11.1.min.js
target: http://spark-master:8080/static/jquery-1.11.1.min.js
get: /proxy:spark-master:8080/static/vis.min.js
host: spark-master:8080
path: /static/vis.min.js
target: http://spark-master:8080/static/vis.min.js
get: /proxy:spark-master:8080/static/bootstrap-tooltip.js
host: spark-master:8080
path: /static/bootstrap-tooltip.js
target: http://spark-master:8080/static/bootstrap-tooltip.js
get: /proxy:spark-master:8080/static/table.js
host: spark-master:8080
path: /static/table.js
target: http://spark-master:8080/static/table.js
get: /proxy:spark-master:8080/static/initialize-tooltips.js
host: spark-master:8080
path: /static/initialize-tooltips.js
target: http://spark-master:8080/static/initialize-tooltips.js
10.70.28.0 - - [22/Sep/2016 13:31:49] "GET /proxy:spark-master:8080/static/additional-metrics.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:49] "GET /proxy:spark-master:8080/static/timeline-view.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:50] "GET /proxy:spark-master:8080/static/spark-logo-77x50px-hd.png HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:31:50] "GET /favicon.ico HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081 HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081/static/bootstrap.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081/static/vis.min.css HTTP/1.1" 200 -
get: /proxy:spark-master:8080/static/additional-metrics.js
host: spark-master:8080
path: /static/additional-metrics.js
target: http://spark-master:8080/static/additional-metrics.js
get: /proxy:spark-master:8080/static/timeline-view.js
host: spark-master:8080
path: /static/timeline-view.js
target: http://spark-master:8080/static/timeline-view.js
get: /proxy:spark-master:8080/static/spark-logo-77x50px-hd.png
host: spark-master:8080
path: /static/spark-logo-77x50px-hd.png
target: http://spark-master:8080/static/spark-logo-77x50px-hd.png
get: /favicon.ico
host: spark-master:8080
path: /favicon.ico
target: http://spark-master:8080/favicon.ico
get: /proxy:10.70.20.3:8081
host: 10.70.20.3:8081
path:
target: http://10.70.20.3:8081
get: /proxy:10.70.20.3:8081/static/bootstrap.min.css
host: 10.70.20.3:8081
path: /static/bootstrap.min.css
target: http://10.70.20.3:8081/static/bootstrap.min.css
get: /proxy:10.70.20.3:8081/static/vis.min.css
host: 10.70.20.3:8081
path: /static/vis.min.css
target: http://10.70.20.3:8081/static/vis.min.css
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081/static/webui.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081/static/timeline-view.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081/static/sorttable.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081/static/jquery-1.11.1.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:36] "GET /proxy:10.70.20.3:8081/static/vis.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:37] "GET /proxy:10.70.20.3:8081/static/bootstrap-tooltip.js HTTP/1.1" 200 -
get: /proxy:10.70.20.3:8081/static/webui.css
host: 10.70.20.3:8081
path: /static/webui.css
target: http://10.70.20.3:8081/static/webui.css
get: /proxy:10.70.20.3:8081/static/timeline-view.css
host: 10.70.20.3:8081
path: /static/timeline-view.css
target: http://10.70.20.3:8081/static/timeline-view.css
get: /proxy:10.70.20.3:8081/static/sorttable.js
host: 10.70.20.3:8081
path: /static/sorttable.js
target: http://10.70.20.3:8081/static/sorttable.js
get: /proxy:10.70.20.3:8081/static/jquery-1.11.1.min.js
host: 10.70.20.3:8081
path: /static/jquery-1.11.1.min.js
target: http://10.70.20.3:8081/static/jquery-1.11.1.min.js
get: /proxy:10.70.20.3:8081/static/vis.min.js
host: 10.70.20.3:8081
path: /static/vis.min.js
target: http://10.70.20.3:8081/static/vis.min.js
get: /proxy:10.70.20.3:8081/static/bootstrap-tooltip.js
host: 10.70.20.3:8081
path: /static/bootstrap-tooltip.js
target: http://10.70.20.3:8081/static/bootstrap-tooltip.js
get: /proxy:10.70.20.3:8081/static/initialize-tooltips.js
host: 10.70.20.3:8081
path: /static/initialize-tooltips.js
10.70.28.0 - - [22/Sep/2016 13:32:37] "GET /proxy:10.70.20.3:8081/static/initialize-tooltips.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:37] "GET /proxy:10.70.20.3:8081/static/table.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:37] "GET /proxy:10.70.20.3:8081/static/additional-metrics.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:37] "GET /proxy:10.70.20.3:8081/static/timeline-view.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:37] "GET /proxy:10.70.20.3:8081/static/spark-logo-77x50px-hd.png HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:32:38] "GET /favicon.ico HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/spark-ui-proxy.py", line 19, in do_GET
    self.proxyRequest(None)
  File "/spark-ui-proxy.py", line 35, in proxyRequest
    proxiedRequest = urllib2.urlopen(targetUrl, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Try again>
target: http://10.70.20.3:8081/static/initialize-tooltips.js
get: /proxy:10.70.20.3:8081/static/table.js
host: 10.70.20.3:8081
path: /static/table.js
target: http://10.70.20.3:8081/static/table.js
get: /proxy:10.70.20.3:8081/static/additional-metrics.js
host: 10.70.20.3:8081
path: /static/additional-metrics.js
target: http://10.70.20.3:8081/static/additional-metrics.js
get: /proxy:10.70.20.3:8081/static/timeline-view.js
host: 10.70.20.3:8081
path: /static/timeline-view.js
target: http://10.70.20.3:8081/static/timeline-view.js
get: /proxy:10.70.20.3:8081/static/spark-logo-77x50px-hd.png
host: 10.70.20.3:8081
path: /static/spark-logo-77x50px-hd.png
target: http://10.70.20.3:8081/static/spark-logo-77x50px-hd.png
get: /favicon.ico
host: spark-master:8080
path: /favicon.ico
target: http://spark-master:8080/favicon.ico
get: /proxy:spark-master:8080
host: spark-master:8080
path:
target: http://spark-master:8080
----------------------------------------
Exception happened during processing of request from ('10.70.28.0', 53708)
----------------------------------------
10.70.28.0 - - [22/Sep/2016 13:33:29] "GET /proxy:spark-master:8080 HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:29] "GET /proxy:spark-master:8080/static/bootstrap.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:29] "GET /proxy:spark-master:8080/static/vis.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:29] "GET /proxy:spark-master:8080/static/webui.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:29] "GET /proxy:spark-master:8080/static/timeline-view.css HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/spark-ui-proxy.py", line 19, in do_GET
    self.proxyRequest(None)
  File "/spark-ui-proxy.py", line 35, in proxyRequest
    proxiedRequest = urllib2.urlopen(targetUrl, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Try again>
get: /proxy:spark-master:8080
host: spark-master:8080
path:
target: http://spark-master:8080
get: /proxy:spark-master:8080/static/bootstrap.min.css
host: spark-master:8080
path: /static/bootstrap.min.css
target: http://spark-master:8080/static/bootstrap.min.css
get: /proxy:spark-master:8080/static/vis.min.css
host: spark-master:8080
path: /static/vis.min.css
target: http://spark-master:8080/static/vis.min.css
get: /proxy:spark-master:8080/static/webui.css
host: spark-master:8080
path: /static/webui.css
target: http://spark-master:8080/static/webui.css
get: /proxy:spark-master:8080/static/timeline-view.css
host: spark-master:8080
path: /static/timeline-view.css
target: http://spark-master:8080/static/timeline-view.css
get: /proxy:spark-master:8080/static/sorttable.js
host: spark-master:8080
path: /static/sorttable.js
target: http://spark-master:8080/static/sorttable.js
----------------------------------------
Exception happened during processing of request from ('10.70.28.0', 53731)
----------------------------------------
10.70.28.0 - - [22/Sep/2016 13:33:34] "GET /proxy:spark-master:8080/static/jquery-1.11.1.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:39] "GET /proxy:spark-master:8080/static/vis.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:39] "GET /proxy:spark-master:8080/static/bootstrap-tooltip.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:39] "GET /proxy:spark-master:8080/static/table.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:39] "GET /proxy:spark-master:8080/static/additional-metrics.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:39] "GET /proxy:spark-master:8080/static/initialize-tooltips.js HTTP/1.1" 200 -
get: /proxy:spark-master:8080/static/jquery-1.11.1.min.js
host: spark-master:8080
path: /static/jquery-1.11.1.min.js
target: http://spark-master:8080/static/jquery-1.11.1.min.js
get: /proxy:spark-master:8080/static/vis.min.js
host: spark-master:8080
path: /static/vis.min.js
target: http://spark-master:8080/static/vis.min.js
get: /proxy:spark-master:8080/static/bootstrap-tooltip.js
host: spark-master:8080
path: /static/bootstrap-tooltip.js
target: http://spark-master:8080/static/bootstrap-tooltip.js
get: /proxy:spark-master:8080/static/table.js
host: spark-master:8080
path: /static/table.js
target: http://spark-master:8080/static/table.js
get: /proxy:spark-master:8080/static/additional-metrics.js
host: spark-master:8080
path: /static/additional-metrics.js
target: http://spark-master:8080/static/additional-metrics.js
get: /proxy:spark-master:8080/static/initialize-tooltips.js
host: spark-master:8080
path: /static/initialize-tooltips.js
target: http://spark-master:8080/static/initialize-tooltips.js
get: /proxy:spark-master:8080/static/timeline-view.js
10.70.28.0 - - [22/Sep/2016 13:33:39] "GET /proxy:spark-master:8080/static/timeline-view.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:40] "GET /proxy:spark-master:8080/static/spark-logo-77x50px-hd.png HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:33:40] "GET /favicon.ico HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:52] "GET /proxy:10.70.20.3:8081 HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:52] "GET /proxy:10.70.20.3:8081/static/bootstrap.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:52] "GET /proxy:10.70.20.3:8081/static/vis.min.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:52] "GET /proxy:10.70.20.3:8081/static/webui.css HTTP/1.1" 200 -
path: /static/spark-logo-77x50px-hd.png
target: http://spark-master:8080/static/spark-logo-77x50px-hd.png
get: /favicon.ico
host: spark-master:8080
path: /favicon.ico
target: http://spark-master:8080/favicon.ico
----------------------------------------
Exception happened during processing of request from ('10.70.28.0', 53987)
----------------------------------------
get: /proxy:10.70.20.3:8081
host: 10.70.20.3:8081
path:
target: http://10.70.20.3:8081
get: /proxy:10.70.20.3:8081/static/bootstrap.min.css
host: 10.70.20.3:8081
path: /static/bootstrap.min.css
target: http://10.70.20.3:8081/static/bootstrap.min.css
get: /proxy:10.70.20.3:8081/static/vis.min.css
host: 10.70.20.3:8081
path: /static/vis.min.css
target: http://10.70.20.3:8081/static/vis.min.css
get: /proxy:10.70.20.3:8081/static/webui.css
host: 10.70.20.3:8081
path: /static/webui.css
target: http://10.70.20.3:8081/static/webui.css
get: /proxy:10.70.20.3:8081/static/timeline-view.css
host: 10.70.20.3:8081
path: /static/timeline-view.css
10.70.28.0 - - [22/Sep/2016 13:39:52] "GET /proxy:10.70.20.3:8081/static/timeline-view.css HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:52] "GET /proxy:10.70.20.3:8081/static/sorttable.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:52] "GET /proxy:10.70.20.3:8081/static/jquery-1.11.1.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:53] "GET /proxy:10.70.20.3:8081/static/vis.min.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:53] "GET /proxy:10.70.20.3:8081/static/bootstrap-tooltip.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:53] "GET /proxy:10.70.20.3:8081/static/initialize-tooltips.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:53] "GET /proxy:10.70.20.3:8081/static/table.js HTTP/1.1" 200 -
target: http://10.70.20.3:8081/static/timeline-view.css
get: /proxy:10.70.20.3:8081/static/sorttable.js
host: 10.70.20.3:8081
path: /static/sorttable.js
target: http://10.70.20.3:8081/static/sorttable.js
get: /proxy:10.70.20.3:8081/static/jquery-1.11.1.min.js
host: 10.70.20.3:8081
path: /static/jquery-1.11.1.min.js
target: http://10.70.20.3:8081/static/jquery-1.11.1.min.js
get: /proxy:10.70.20.3:8081/static/vis.min.js
host: 10.70.20.3:8081
path: /static/vis.min.js
target: http://10.70.20.3:8081/static/vis.min.js
get: /proxy:10.70.20.3:8081/static/bootstrap-tooltip.js
host: 10.70.20.3:8081
path: /static/bootstrap-tooltip.js
target: http://10.70.20.3:8081/static/bootstrap-tooltip.js
get: /proxy:10.70.20.3:8081/static/initialize-tooltips.js
host: 10.70.20.3:8081
path: /static/initialize-tooltips.js
target: http://10.70.20.3:8081/static/initialize-tooltips.js
get: /proxy:10.70.20.3:8081/static/table.js
host: 10.70.20.3:8081
path: /static/table.js
target: http://10.70.20.3:8081/static/table.js
get: /proxy:10.70.20.3:8081/static/additional-metrics.js
10.70.28.0 - - [22/Sep/2016 13:39:53] "GET /proxy:10.70.20.3:8081/static/additional-metrics.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:53] "GET /proxy:10.70.20.3:8081/static/timeline-view.js HTTP/1.1" 200 -
10.70.28.0 - - [22/Sep/2016 13:39:53] "GET /proxy:10.70.20.3:8081/static/spark-logo-77x50px-hd.png HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/spark-ui-proxy.py", line 19, in do_GET
    self.proxyRequest(None)
  File "/spark-ui-proxy.py", line 35, in proxyRequest
    proxiedRequest = urllib2.urlopen(targetUrl, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Try again>

```

**Comment by ursuad** [comment]
Apparently the problem was on my side with the DNS resolver, sometime the service name wasn't resolved. 
I'll mark the issue as closed.
